### ISSUE TITLE
New release for Swift 4.2?

### ISSUE THREAD

**Issue by bill350** [andrealufino/Luminous#13]
I saw [Swift 4.2 compatibility](https://github.com/andrealufino/Luminous/commit/d9c67256ff93b3566eda1299c5db6a404a0a15fd) but no related release.
It's time to create a `1.1`, is it possible to release and submit it on Cocoapods?

Thanks

**Comment by andrealufino** [comment]
Hello! Sorry for the late response. I have pushed a `1.10` version, also on Cocoapods with compatibility with Swift 5.
