### ISSUE TITLE
No more CNCopyCurrentNetworkInfo access

### ISSUE THREAD

**Issue by bill350** [andrealufino/Luminous#16]
# iOS 13 breaking change on SSID network

Apple does not grant access to `CNCopyCurrentNetworkInfo` API anymore, as communicated by Apple on August 7th, 2019 : 
> 
> As we announced at WWDC19, we're making changes to further protect user privacy and prevent unauthorized location tracking. Starting with iOS 13, the `CNCopyCurrentNetworkInfo` API will no longer return valid Wi-Fi SSID and BSSID information. 
>
> Instead, the information returned by default will be:   
> - **SSID: “Wi-Fi” or “WLAN” (“WLAN" will be returned for the China SKU)**
> -  **BSSID: "00:00:00:00:00:00"   If your app is using this API, we encourage you to adopt alternative approaches that don’t require Wi-Fi or network information.** 
>
> Valid SSID and BSSID information from `CNCopyCurrentNetworkInfo` will still be provided to VPN apps, apps that have used `NEHotspotConfiguration` to configure the current Wi-Fi network, and apps that have obtained permission to access user location through Location Services.   Test your app on the latest iOS 13 beta to make sure it works properly. 
>
> If your app requires valid Wi-Fi SSID and BSSID information to function, you can do the following:
> 	•	For accessory setup apps, use the `NEHotSpotConfiguration` API, which now has the option to pass a prefix of the SSID hotspot your app expects to connect to.
> 	•	For other types of apps, use the CoreLocation API to request the user’s consent to access location information.

## Solution

- Use alternative API to get SSID information

**Comment by andrealufino** [comment]
I tried to make some research about this, but I didn't find a decent solution. For the next version of Luminous, I will deprecate `SSID` var for iOS 13. 
If someone has found a solution, I'm all ears.
