### ISSUE TITLE
pod install issue

### ISSUE THREAD

**Issue by bauersfeld** [andrealufino/Luminous#2]
[!] Unable to find a specification for `Luminous`

Here is the podfile

platform :ios, '10.0'
use_frameworks!

target 'my_tutorial' do
    pod 'Luminous'
end

**Comment by andrealufino** [comment]
Hello. This is strange. Obviously the Podspec file is well written and is active (you can check on the cocoapods website). Luminous requires iOS 8+ so even with the system there shouldn't be problems. I found [this stackoverflow answer](http://stackoverflow.com/a/32850706/588967) so please try to check it.

**Comment by bauersfeld** [comment]
that worked!  much appreciated

**Comment by andrealufino** [comment]
Great :)
