### ISSUE TITLE
Problems with SystemVersion

### ISSUE THREAD

**Issue by GregOriol** [andrealufino/Luminous#20]
Hi @andrealufino,

I have 2 issues with the SystemVersion struct:
1/ it seems that major, minor and path values are currently all set to the "first" component
```
            major = Int(components.first!)!
            minor = Int(components.first!)!
            patch = Int(components.first!)!
```
which doesn't seem correct?

2/ there doesn't seem to be any way to retrieve any of the values, either major/minor/patch or the full string value as everything is private, which makes it mostly useless?

**Comment by andrealufino** [comment]
The pull request @GregOriol made should fix the problem. Thanks @GregOriol 👍🏻
