### ISSUE TITLE
replace functions with vars

### ISSUE THREAD

**Issue by neoneye** [andrealufino/Luminous#3]
There are many functions without arguments.

It would be nice if parenthesis can be omitted.

Instead of invoking `isConnectedViaWiFi()`, then invoke `isConnectedViaWiFi`

**Comment by andrealufino** [comment]
Do you think this would be a better way? I was undecided during the development on which method use, functions or vars

**Comment by neoneye** [comment]
My personal preference is something like this: 

```
var isConnected: Bool {
    do stuff 
    return true 
}
```

**Comment by andrealufino** [comment]
Yes, I think would be better. I'll add it to the todos

**Comment by andrealufino** [comment]
Done in version 0.50.00
