### ISSUE TITLE
Carthage installation

### ISSUE THREAD

**Issue by ghost** [andrealufino/Luminous#4]
Please add Carthage as a way of installing Luminous!

Some are articles to help you:

- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/9pVzFX)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods ](https://goo.gl/mzZ3Si)

On your `README.md` add [![Carthage Compatible](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)](https://github.com/Carthage/Carthage) on top and add section for the installation with Carthage.

**Comment by andrealufino** [comment]
I'm not a fan of Carthage and I don't know how to implement it. For now I can only wait for Pull Request for this so.
