### ISSUE TITLE
Luminous.Carrier.networkCountryCode should be .mobileNetworkCode

### ISSUE THREAD

**Issue by ethanhuang13** [andrealufino/Luminous#5]
I haven't use this library, just saw your source code.

I think Luminous.Carrier.networkCountryCode should be .mobileNetworkCode(MNC) in 
https://github.com/andrealufino/Luminous/blob/master/Luminous/Classes/Luminous.swift

**Comment by ethanhuang13** [comment]
It's also carrierMobileNetworkCode in ALSystemUtilities.

https://github.com/andrealufino/ALSystemUtilities/blob/develop/ALSystemUtilities/ALSystemUtilities/ALCarrier/ALCarrier.m

**Comment by andrealufino** [comment]
Yes, you're right. 
Done in version 0.50.30, already published on cocoapods. 
[This](https://github.com/andrealufino/Luminous/commit/cc02e0636919c87eb00fbe22692b19657049f81b) is the interested commit.
